language: python
python:
- 3.8
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: theRealBithive
  password:
    secure: Yeg3jfijb+nVz523QhBQOV0Q2Roh/JUjx8qwv0jtGcmyld1bU70wpGxck6w/A2YJs4D2O9M7Qu2axabNcfd4aRU/B/m3ZALTrqvf89PX3pi2A/ivD2cuEQM7TPvHHPF8sUfzbwubrsI0vc5tiDMqiqdbmlOuITYQAwvBUjUFSpP4Ie9HmGKdfS3h33xREelyYerC1UldoUx9slDZtQ8hWXqHV0iECaMD1ky08OawTcIJApYZbCDl+i0iaCfGa+MDeGND4FCl02OapHczP/LLtb1K+5I2ezF56KcZLKWmjCftxSAl+d7ibQ6Yo9Hu75tK1kZVafS9PBf/ItatU+Qm0ZWecnIOaLTrR4RpBQvmxeMEP4nByJ6VgptViZCbXg4FnGBBY1B+6DAE6mjPcBx0GpkD8897vjwBX+AoMYGHzVgNoEN2XJ759ZX0fm5wSVUtYtylbHzmVWtpbaRFeJOubR5Cun3WLu5BtYdKmShDfjn/iMyzUHmeWLbCMK7Y3Fcnvps88oZqdUnSzjWJKBL34zooKPYkOZZybAzQDt2xL394rSOyzNyYRyW12nSybFdqZfTAOYu96Qk3b1g5j7oyinMuZHoGgS/iCG9fLJz072BPvm1p5730LX2c4KFS/VA1Bk5OBl6tZG8Ee3DlkwJogAY8KGY6T8BMHAQZkt2vJhU=
  on:
    tags: true
    repo: theRealBithive/lexofficepyapi
    python: 3.8
env:
  global:
    secure: fHZ156ai11YvRfkRFHXPRZ2d40dj2xGYQRPKxyFe6U4j5K67Ds+MdiZjxk2QBB4tFYzhXszwADS5qf//9O/HwigGd3lktXDEqzUsgJn03y8CWVvqoxlXMbZWR+OWyYR4R0UNXrem3rydyYys96/ck21/isyBn1mc4gyI89rCJHQqJIw5auuepJUd+Z4jBe7EMOCmXqS1Bu0m7uYqmoQajeQpY/eu7rVM5LCzGuLN5y4k6lF3Y081fpQCwn7Cm9nj9th0hcN3uvWbxJ/rLv6pyKNMnsa/cVGL4EHzELvkk5SADhkOn/cQ6QR9+u3iji5J8z/o+oJ1hOiWgpt2RrbpsjVX1R+Xs6ZokBL9PK7VR760KYdA6rFSS4WNIH4WiLFbUJAuEEYvTEMZmVGpZeyTB+TO2Iexz9lKd9hlJBU7KrMn+pNdSJmFuM29ekSmSLFZjNXQUoFQ8FpODPLyoMWUSzpBv8VsHyx3O3D+UjqghtC5R9+7oANQ4eJwPVRYD0vX3Lh1tOIDabcyrVZXk62KxYglXOJvLm19YXM0/oElXfwA+J0PQSRESgo9V1+BFSvDOtACMLVwXB6vhXQsN1w5CGxeMvt1wE2ZalFeacZtTlJmI7cM9/3rsDLQd4Y1bfcJJGlJv0TmdGky0MUCDjPjfg0P4lDt5QqSrp7ugTvIqDc=
