language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: theRealBithive
  password:
    secure: Yeg3jfijb+nVz523QhBQOV0Q2Roh/JUjx8qwv0jtGcmyld1bU70wpGxck6w/A2YJs4D2O9M7Qu2axabNcfd4aRU/B/m3ZALTrqvf89PX3pi2A/ivD2cuEQM7TPvHHPF8sUfzbwubrsI0vc5tiDMqiqdbmlOuITYQAwvBUjUFSpP4Ie9HmGKdfS3h33xREelyYerC1UldoUx9slDZtQ8hWXqHV0iECaMD1ky08OawTcIJApYZbCDl+i0iaCfGa+MDeGND4FCl02OapHczP/LLtb1K+5I2ezF56KcZLKWmjCftxSAl+d7ibQ6Yo9Hu75tK1kZVafS9PBf/ItatU+Qm0ZWecnIOaLTrR4RpBQvmxeMEP4nByJ6VgptViZCbXg4FnGBBY1B+6DAE6mjPcBx0GpkD8897vjwBX+AoMYGHzVgNoEN2XJ759ZX0fm5wSVUtYtylbHzmVWtpbaRFeJOubR5Cun3WLu5BtYdKmShDfjn/iMyzUHmeWLbCMK7Y3Fcnvps88oZqdUnSzjWJKBL34zooKPYkOZZybAzQDt2xL394rSOyzNyYRyW12nSybFdqZfTAOYu96Qk3b1g5j7oyinMuZHoGgS/iCG9fLJz072BPvm1p5730LX2c4KFS/VA1Bk5OBl6tZG8Ee3DlkwJogAY8KGY6T8BMHAQZkt2vJhU=
  on:
    tags: true
    repo: theRealBithive/lexofficepyapi
    python: 3.8
test:
  api_key:
    secure: oX0K+fHU8Civ/8mloWcU9AMZ/APGMZxP4NIYhPC9lQRRwRqDFvh8KpW7npesIXf7A6y0bGF30CFDSMwGdC9+FgrqBhbIiG8hDY5LlM1vQyCKfu5EqqkCIaNk0Ud/9P+6WN7Aa+X+AfXgYKt93RzPfRC6AVq8ZLaWNOdCQ1P6aJtyKYUCiIpO63bNn7NqoWlfUEIzTZZNOmrO4VDvcw9scxmFuudVc82/BZlC7gXX7XU05+cJ98hPwpdvPb5d6e6UEWdhIWtiYokNsmlFKLC87NH5atVuf5CLHMf+w0jI0UP6lgCbf8hiy6DatJ4UVtqbDyanYKK22kJq5Lrsvb3TNtP7T1s+gnqrEQxKJZyRBvXVCRtjG8RVK+sy1wiYcDXFg5FYwkgrum7N+pM8TQjqFBkRMQyD7wEQquLYa1YqfKMYorywObkFiKEKMT9SlJqwDvTuVeOAUO85plETnXN8sXA5NbBZIJR6LNk5Lxk2mxPK+/5R20KHW1gGN0XZ5fB0jt2h2VrNWR5/GnJ4CZriuZhmv4D8eBWhxkJThOvQHXI0Q+cgoFQfMffxfuCXNzyTmPziWwketE/Q1pf0aH3M9t3Rne0fjJWl5t46ctoNVheoI4KkyjIDaXhdwRMVIeFXD4teqrt/EooP4jH2WNlG2z0iyQbdDHLg/vRr06ZGab4=
env:
  global:
    secure: BV2wUsfH6pUMuKoCoblbUvyj26NK9Uu96HcHhGnQVQCEM8SDmtVZanSsKk0uqkB/OhaPwjir1VK92VqaF/9R0/CCxUG4Acvl6QBz+yDBzoFXJDLzdpNjBejzOL1FOARAk9eUROchgARQKi9nS7uEDxLDocWnmnJSMbpv6BNxKLfi4+2VRXR9xSZl95P89O/WlXBuvBAwYcm8pLq1vnCLrjWGj2iv8/fj6awH+wu+OUBF13JxPOVGWe1D76WowuyVy/DaLrLUsITdBosLpqQkYeaObX7kNy1Wcg0BH3CkvE7ZT2XJy+U/h78TUxmjVCQUP/exGXQiLsnWlvqd2vxoXgUW/N/pIVeBIr6DNDZ2gtJ3gcWODbURaKWNiXkrkslhCHRIXBHmzMqusF1+X+4EBdzHyI3/FH8dR4o66euGeieLdSAky3YnagpFpJL4kZ2fKvJkYI7DQIkuQ9txtLBeuCjCkF899FNyQUxAAtHaAqbJo3tE7QoXC3w6MJySU/JNF22pLIQeobdOLd9goqfE2BLYfYwpCwrTS1DOGQ/GwyKpXFN/tMbt8/W1bEOz17wvB0SLGjXzUNpYMATqIJT6a1IIDd+qyQ8DTxUMlfsf7NWuU3hHi91Ni4vuRzLyyE689AaMmT1Pwbq9jYp5zhQOZFhxzKVT9dVFlSUB1h7fBHc=
